[package]
name = "pass_manager"
version = "0.1.0"
edition = "2021"

[dependencies]
aes-gcm-siv = "0.10"
base64 = "0.13"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rand = "0.8"
sha2 = "0.10"
rpassword = "7.3.1"